# The workflow builds if the test workflow succeeds.

name: Build

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'triggering worflow has failed'

  buildpackages:
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo 'it will build packages here'